### PR TITLE
Fix/dropbox 

### PR DESCRIPTION
**Pull request by daxiondi**
1. to make clear config.js For installation using [Devops guide QuickStart](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart).
2.Do you think it is necessary to highlight the redirect URI in the document?
3.`https://yourdeployment.com//static/oauth.html` Revised as `https://yourdeployment.com//static/oauth.html`
4.Do you think this subfolder is misleading? I think it's better to delete it because it doesn't apply to users who use [Devops guide QuickStart](https://github.com/jitsi/jitsi-meet/blob/master/config.js#L186).

### CODE REVIEW

**Comment by daxiondi** [comment]
@saghul Do you have time to check it out

**Comment by daxiondi** [comment]
@saghul hello，Do you think it necessary for me to submit a [PR](https://github.com/daxiondi/jitsi-meet/commit/62b4d814c686028bd6911e51a18bfc24f8db5eec) to the jitsi meet repository?
 Because the current description is not suitable for Devops guide QuickStart
 there will be ambiguity. If you think it is unnecessary, I will not submit PR and look forward to your reply

**Comment by saghul** [comment]
I think it's ok, because it depends on the user setup. They maybe running Jitsi off a subfolder.

**Comment by daxiondi** [comment]
ok，Have you seen my PR https://github.com/jitsi/jibri/pull/323 
I have a lot of questions about jitsi. Do you have any other contact information? Such as relaxation

**Pull request merged**
