### PR TITLE
Add command and event for the new whiteboard api call

### PR DESCRIPTION
**Pull request by ledzepff**
Update handbook for a newly added whiteboard call to jitsi API. 

Closed PR - https://github.com/jitsi/jitsi-meet/pull/13292

Can be merged right after the next jitsi-meet release

### CODE REVIEW

**Comment by ledzepff** [comment]
Hi @saghul, 

This can be merged now. No release for the handbook yet, let's have the first one )

**Comment by saghul** [comment]
The handbook is a living document, we don't make releases.

**Comment by ledzepff** [comment]
> The handbook is a living document, we don't make releases.

Thanks

**Comment by ledzepff** [comment]
@saghul I've sent you an email at s@saghul.net. Can you please check it when you have time for that? Need your help

**Pull request merged**
