### PR TITLE
renamed the folder and files

### PR DESCRIPTION
**Pull request by YogeshJoshi10072000**
renamed the folder and files

### CODE REVIEW

**Comment by damencho** [comment]
Why is this necessary?

**Comment by YogeshJoshi10072000** [comment]
> Why is this necessary?
#43 issue says it.I am new in open source .This is my first commit in open source as I found it easy to commit

**Comment by damencho** [comment]
Does this keep the links unchanged?

**Comment by saghul** [comment]
No it won't.

**Pull request closed without merging**
