### PR TITLE
Create community-run-instances.md

### PR DESCRIPTION
**Pull request by tosteiner**
Updated and revamped version of the deprecated Wiki page "Jitsi-Meet-Instances" at

https://github.com/jitsi/jitsi-meet/wiki/Jitsi-Meet-Instances

Server list up-to-date (Nov 23, 2020)

### CODE REVIEW

**Comment by saghul** [comment]
Nice! This is not linked on any sidebar section though, right?

**Comment by tosteiner** [comment]
Hi there! ah, yes, that's right - sorry, didn't really know where to put it, but suppose it might be part of either "Getting Started" or "User Guide" sections, maybe?

**Comment by saghul** [comment]
Getting started sounds good!

**Comment by tosteiner** [comment]
Perfect! have included the frontmatter bit (id, title) - not sure if anything else is missing?

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
I think one more thing is needed, but I'll take care of it, no worries.

**Pull request merged**
