### PR TITLE
Add openSUSE guide

### PR DESCRIPTION
**Pull request by SchoolGuy**
We are trying to document our efforts for all interested parties here and are willing to update the docs regularly. We will host a public instance with this guide and thus think it would be appropriate to share this with the community.

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@nodeg was a viable part in creating this guide.

**Comment by saghul** [comment]
Thanks for this! Some of us are taking some time off, we'll review it soon!

**Comment by SchoolGuy** [comment]
@saghul Remember that this is not finished. We need to improve the `rpm` packages and get it in our distro. Also we maybe want to extend this because I wrote this guide in maybe half an hour and did not look at possible missed points. But thanks for the initial feedback! :)

**Comment by m-rey** [comment]
I've made some further changes to improve readability and fix some typos.

**Comment by SchoolGuy** [comment]
@saghul We would be ready for reviews!

**Comment by SchoolGuy** [comment]
@saghul Any news?

**Comment by SchoolGuy** [comment]
@saghul Is there anything we can do to progress this? Otherwise I would just close it. Leaving it open for eternity is not something I would like...

**Comment by SchoolGuy** [comment]
No activity from upstream sadly. I ported the page to - https://en.opensuse.org/SDB:Jitsi

Please reopen if you are interested in having openSUSE. We would of course maintain the guide as openSUSE Contributors for ourselves and update it regularly.

**Comment by saghul** [comment]
Sorry I dropped the ball on this one. Around the time when it was opened last year was when we could finally get a bit of rest. Please do rebase it and let's land it.

**Comment by nodeg** [comment]
Thanks for picking this up again, @saghul. Rebase done.

**Review by saghul — APPROVED** [review]

**Pull request merged**
