### PR TITLE
Cherry picking PRs on documents at jitsi-meet

### PR DESCRIPTION
**Pull request by luixxiul**
Closes https://github.com/jitsi/jitsi-meet/pull/5940
Closes https://github.com/jitsi/jitsi-meet/pull/5960
Closes https://github.com/jitsi/jitsi-meet/pull/6018
Closes https://github.com/jitsi/jitsi-meet/pull/6063
Closes https://github.com/jitsi/jitsi-meet/pull/6080
Closes https://github.com/jitsi/jitsi-meet/pull/6278
Closes https://github.com/jitsi/jitsi-meet/pull/6352
Closes https://github.com/jitsi/jitsi-meet/pull/6726
Closes https://github.com/jitsi/jitsi-meet/pull/5924
Closes https://github.com/jitsi/jitsi-meet/pull/6023

### CODE REVIEW

**Comment by luixxiul** [comment]
@saghul Finished cherry-picking PRs at https://github.com/jitsi/jitsi-meet/pulls?q=is%3Apr+is%3Aopen+label%3Adocumentation

I have also singed CLA on docusign.

**Comment by saghul** [comment]
This is awesome, thank you!

**Comment by luixxiul** [comment]
Still some PRs on API were left unpicked as I was not sure if they were proper proposal.

- https://github.com/jitsi/jitsi-meet/pull/6077
- https://github.com/jitsi/jitsi-meet/pull/6396
- https://github.com/jitsi/jitsi-meet/pull/6545

Also these ones:

- https://github.com/jitsi/jitsi-meet/pull/5580
- https://github.com/jitsi/jitsi-meet/pull/6053

**Comment by saghul** [comment]
I’ll check those. Thanks for listing them, this really helps!

**Comment by denis-trofimov** [comment]
@luixxiul @Syonyk
the passage about #### Other Issues with WEBPACK_DEV_SERVER_PROXY_TARGET is not deployed to https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-web

**Comment by luixxiul** [comment]
Please see above: https://github.com/jitsi/handbook/pull/1#issuecomment-629804358

> Also these ones:
> 
>     * [jitsi/jitsi-meet#5580](https://github.com/jitsi/jitsi-meet/pull/5580)
> 
>     * [jitsi/jitsi-meet#6053](https://github.com/jitsi/jitsi-meet/pull/6053)
> 
> 
> For now I would leave them as they are.

I didn't touch the PR https://github.com/jitsi/jitsi-meet/pull/6053, and I'm not sure why that commit was not merged here.

**Pull request merged**
