### PR TITLE
Fix npm install failed 

### PR DESCRIPTION
**Pull request by daxiondi**
Following the last [pr](https://github.com/jitsi/handbook/pull/67)

### CODE REVIEW

**Comment by daxiondi** [comment]
@toby63

**Comment by daxiondi** [comment]
@toby63 I am waiting for your code review.

**Comment by toby63** [comment]
@daxiondi Can you rebase and squash the 6 commits into one?
Otherwise it looks good to me now.

 @saghul Review requested.

**Comment by daxiondi** [comment]
@saghul Waiting for your code review

**Comment by saghul** [comment]
Thanks!

**Comment by daxiondi** [comment]
@saghul hi，Do you have time to read this [PR](https://github.com/jitsi/handbook/pull/68)? I need your help.
Thanks @toby63 .

**Pull request merged**
