### PR TITLE
Add ldap authentication, fixes #224

### LINKED ISSUE #224: LDAP
Would be great if you could cover LDAP from here: https://github.com/jitsi/jitsi-meet/wiki/LDAP-Authentication - but with official ways how to do it (if there is something missing).

### PR DESCRIPTION
**Pull request by ulab**
This is a first draft for the LDAP authentication section. 

Please let me know if you have any suggestions.

PS: I am not sure how this is added to the sidebar / navigation.

### CODE REVIEW

**Comment by saghul** [comment]
Looks like a good start! You may want to link the document in the sidebar.

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Merged! Sorry, I've been away for a few days.

**Comment by ulab** [comment]
Any idea why the last line of the notes in the formatted document are on their own paragraphs?

**Comment by saghul** [comment]
It doesn't like line breaks very much, I just fixed that.

**Pull request merged**
