### PR TITLE
Fixed outdated links in manual.md

### PR DESCRIPTION
**Pull request by filiprejmus**
PR for #284 
The guide is still outdated regarding part of the instructions but possible workarounds have been discussed in https://community.jitsi.org/t/dowload-jitsi-videobridge-404/67825 so posting that for visibility

### CODE REVIEW

**Comment by saghul** [comment]
Hum, those links should be working, I'll take a look, something may have broken after the v2 migration.

The JVB change is not really correct at any rate is it?

**Comment by filiprejmus** [comment]
Oh, no Idea why I was getting a 404 but yes they seem to work.
Regarding JVB I was thinking that while the manual installation changed with the removal of zips, it could be better to provide a correct link of the jvb deb files at https://download.jitsi.org/stable/.
Example config link is definitely outdated though, I think the new link should be correct.

**Comment by saghul** [comment]
Sounds good, can you please adjust the PR?

**Comment by filiprejmus** [comment]
sorry messed up my git tree while trying to squash into one commit

**Comment by filiprejmus** [comment]
anyway, I now there is the updated example config link and a warning that gives hints how to install jvb manually.

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Cheers!

**Pull request merged**
